// import { ImobileProduct } from "../models/postsinterface";


export const mobileProducts   = [
    {
      id: 1,
      name: 'iPhone 13',
      brand: 'Apple',
      price: 999,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: 'https://i.insider.com/6116b065c040ad0018ce3ea1?width=1009&format=jpeg',
      isAvailable: true,
    },
    {
      id: 2,
      name: 'Samsung Galaxy S21',
      brand: 'Samsung',
      price: 899,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: '',
      isAvailable: false,
    },
    {
      id: 3,
      name: 'Google Pixel 6',
      brand: 'Google',
      price: 799,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: 'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios16-iphone13-pro-widgets-home-screen.png',
      isAvailable: true,
    },
    {
      id: 4,
      name: 'OnePlus 9 Pro',
      brand: 'OnePlus',
      price: 899,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: '',
      isAvailable: true,
    },
    {
      id: 5,
      name: 'Xiaomi Mi 11',
      brand: 'Xiaomi',
      price: 699,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
    },
    {
      id: 6,
      name: 'Sony Xperia 1 III',
      brand: 'Sony',
      price: 1199,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: '',
      isAvailable: true,
    },
    {
      id: 7,
      name: 'LG Velvet',
      brand: 'LG',
      price: 599,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: '',
      isAvailable: false,
    },
    {
      id: 8,
      name: 'Huawei P40 Pro',
      brand: 'Huawei',
      price: 899,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: '',
      isAvailable: true,
    },
    {
      id: 9,
      name: 'Motorola Moto G Power',
      brand: 'Motorola',
      price: 249,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
    },
    {
      id: 10,
      name: 'Nokia 8.3',
      brand: 'Nokia',
      price: 499,
      color : 'Blue',
      Sim_Type : 'Dual',
      in_Box : 'Handset, USB Power, USB Cable, Sim Eject Tool,',
      image: '',
      isAvailable: true,
    }
  
  ];